### ISSUE TITLE
Seeking resources for React performance optimization

### ISSUE THREAD

**Issue by phuchoa2001** [deepakkumar55/ULTIMATE-JAVASCRIPT-PROJECT#9]
I'm very interested in JavaScript performance and optimization, especially in the context of ReactJS. Do you have any resources or documentation on this topic? I would like to learn more about it from you

**Comment by thegeek36** [comment]
### Hey you can check these out

- https://react.dev/reference/react/Profiler
- https://medium.com/@itsanuragjoshi/code-splitting-for-react-dynamic-imports-lazy-loading-and-suspense-explained-1ce3c8dde2c8
- Memoization and PureComponent

**Comment by phuchoa2001** [comment]
Thank you for sharing these resources.
